[build]
  base = "frontend/frontpage"
  publish = "frontend/frontpage/build"
  command = "npm install && npm run build"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"